# Name: Ascii
# Description: A prompt using only ASCII characters.

ZSH_GIT_PROMPT_SHOW_UPSTREAM="no"

ZSH_THEME_GIT_PROMPT_PREFIX=" "
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_SEPARATOR=" "
ZSH_THEME_GIT_PROMPT_DETACHED="%F{cyan}:"
ZSH_THEME_GIT_PROMPT_BRANCH="%F{magenta}"
ZSH_THEME_GIT_PROMPT_UPSTREAM_SYMBOL="%F{yellow}^"
ZSH_THEME_GIT_PROMPT_UPSTREAM_PREFIX="%F{red}(%F{yellow}"
ZSH_THEME_GIT_PROMPT_UPSTREAM_SUFFIX="%F{red})"
ZSH_THEME_GIT_PROMPT_BEHIND="%F{red}v"
ZSH_THEME_GIT_PROMPT_AHEAD="%F{green}^"
ZSH_THEME_GIT_PROMPT_UNMERGED="%F{red}x"
ZSH_THEME_GIT_PROMPT_STAGED="%F{green}o"
ZSH_THEME_GIT_PROMPT_UNSTAGED="%F{red}+"
ZSH_THEME_GIT_PROMPT_UNTRACKED=".."
ZSH_THEME_GIT_PROMPT_STASHED="%F{blue}$"
ZSH_THEME_GIT_PROMPT_CLEAN="%F{green}>"

PROMPT='%B%40<..<%~%b$(gitprompt)'
PROMPT+='%(?.%(!.%F{yellow}.%F{green})>%f.%F{red}>%f) '
RPROMPT=''
